# Site settings
title:       Ice cream
email:       alexey@genuss.me
author:      Alexey Genus
description: "Ice cream lover"
baseurl:     ""
url:         "/"

# Google analytics
google_analytics: UA-59763310-1

# Optional features
animated:           false
show_related_posts: false

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname: alexeygenus

# Social icons
show_social_icons: true
github_username:   genuss
stackoverflow_id:
twitter_username:
google_plus_id:
linkedin_username:
bitcoin_url:
paypal_url:
flattr_button:

# Build settings
markdown:     redcarpet
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
paginate:     3
sass:
  compressed: true

gems:      ['jekyll/tagging']


# jekyll-tagging
tag_page_layout: tag_page
tag_page_dir: tag
# tag_feed_layout: tag_feed
# tag_feed_dir: tag
